#ifndef NTUTILS_CONFIG_H
#define NTUTILS_CONFIG_H

#ifndef NT_PANIC_MAX_HANDLER_COUNT
#define NT_PANIC_MAX_HANDLER_COUNT 1024
#endif

#ifndef NT_PANIC_EXIT_CODE
#define NT_PANIC_EXIT_CODE 99
#endif

#ifndef NT_READER_MAX_LOOKAHEAD
#define NT_READER_MAX_LOOKAHEAD 4
#endif

#ifndef NT_READER_INTERN_BUFFER_SIZE
#define NT_READER_INTERN_BUFFER_SIZE 8
#endif

#ifndef NT_JSON_MAX_KEY_LEN
#define NT_JSON_MAX_KEY_LEN 64
#endif

#ifndef NT_JSON_MAX_STR_LITERAL_LEN
#define NT_JSON_MAX_STR_LITERAL_LEN 1024
#endif

#ifndef NT_JSON_MAX_DEPTH
#define NT_JSON_MAX_DEPTH 64
#endif

#endif // NTUTILS_CONFIG_H
